arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart


#   keytool -genkey -v -keystore C:\upload-keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias upload
